[package]
name = "packline_core"
version = "0.1.0"
authors = ["Vinícius Jabes <vinijabes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.4.0", features = ["process"] }
async-trait = {version = "0.1.48"}
futures = "0.3.13"

[features]
default = []

all = [
    "protocol",
    "broker"
]

protocol = ["broker"]
broker = []